services:
  debian:
    build:
      args:
        - USER_ID=${UID:-1001}
        - GROUP_ID=${GID:-${UID:-1001}}
      context: .
      dockerfile_inline: |
        FROM debian:latest
        ARG USER_ID
        ARG GROUP_ID
        RUN useradd -u ${USER_ID} -g ${GROUP_ID} -m appuser
        USER appuser
    command: id -u && id -g

